language: ruby
rvm:
  - 2.2.3

before_script:
  - chmod +x ./script/cibuild
  
before_install:
  - gem update bundler

install: gem install jekyll -v 2.5  html-proofer

script: jekyll build && htmlproofer ./_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

exclude: [vendor]

sudo: false
