language: ruby
rvm:
  - 2.2.3


before_install:
  - gem update bundler

install: gem install jekyll rdiscount pygments.rb jekyll-paginate jekyll-seo-tag jekyll-gist redcarpet

script: jekyll build

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

exclude: [vendor]

sudo: false
