# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rohanpande.in/
baseurl: ''
title: Rohan Pande
author: Rohan Pande
description: Personal blog and resume
avatar: profile.jpg
email: info@rohanpande.in
github: rohanpande # username
twitter: justrohu
linkedin: justrohu
#stackoverflow: justrohu   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-85306442-1


# needed for travis-ci build
exclude: [vendor]
