# Dependencies
markdown:         redcarpet
highlighter:      pygments

<<<<<<< HEAD
title: Rohan Pande
desctiption: This has become my personal theme.
url: http://rohanpande.in/
permalink: ':title/'

markdown: kramdown

=======
# Permalinks

>>>>>>> develop


# Setup
title:            Rohan Pande
tagline:          'A Jekyll theme'
description:      'Programming enthusiast, Nature lover, Open source contributor'
url:              http://hyde.getpoole.com
baseurl:          /
gems: [jekyll-paginate, jekyll-gist, rb-pygments]

<<<<<<< HEAD

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-44574967-4

# Comments
disqus-shortname: www-rohanpande-in

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:

include: [_pages]
version: 0.8

gems: [jekyll-paginate, jekyll-seo-tag]
=======
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
>>>>>>> develop
