# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rohan Pande
email: justrohu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Graphic Artist - User Experience Designer
baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "http://rohan.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: justrohu
github_username:  rohanpande
facebook_username: justrohu
instagram_username: justrohu
#stackoverflow_url: https://
googleplus_username: justrohu
skype_username: justrohu
#linkedin_url: https://

# Address information
address_street: A - 1/10, C.A. Road
address_city: Nagpur
address_state: MH, India
address_zip: 440006

# Build settings
markdown: kramdown
