# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks



# Setup
title:            Rohan Pande
tagline:          'A programmers blog, thought sharing space'
description:      'Programming enthusiast, Nature lover, Open source contributor'
url:              http://www.rohanpande.in
baseurl:          /
gems:             [jekyll-paginate, jekyll-gist]

author:
  name:           'Rohan Pande'
  url:            http://www.rohanpande.in

paginate:         5
