# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks



# Setup
title:            Rohan Pande
tagline:          'A Jekyll theme'
description:      'Programming enthusiast, Nature lover, Open source contributor'
url:              http://hyde.getpoole.com
baseurl:          /
gems: [jekyll-paginate, jekyll-gist, rb-pygments]

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
